# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZjQwNjgwZmVlYjVhNGE4NzQ5MDhhZDI1M2EzOTUwNjM5ZTQ5M2FlZjkyY2E5MDcxN2Q3NTMzZWQ2ZTQwODU0MTU3ZTAwN2NhODIyMzZkZDY5YzZmOWQ0YTgzNzVmYjU0NmE0NjExZGEwNGUxN2I5ZjgzZmUzZTVlMzZlZjZjZjY=
