package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassConceptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassConceptAllPropertiesEquals(ClassConcept expected, ClassConcept actual) {
        assertClassConceptAutoGeneratedPropertiesEquals(expected, actual);
        assertClassConceptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassConceptAllUpdatablePropertiesEquals(ClassConcept expected, ClassConcept actual) {
        assertClassConceptUpdatableFieldsEquals(expected, actual);
        assertClassConceptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassConceptAutoGeneratedPropertiesEquals(ClassConcept expected, ClassConcept actual) {
        assertThat(actual)
            .as("Verify ClassConcept auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassConceptUpdatableFieldsEquals(ClassConcept expected, ClassConcept actual) {
        assertThat(actual)
            .as("Verify ClassConcept relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStereotype()).as("check stereotype").isEqualTo(expected.getStereotype()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassConceptUpdatableRelationshipsEquals(ClassConcept expected, ClassConcept actual) {
        assertThat(actual)
            .as("Verify ClassConcept relationships")
            .satisfies(a ->
                assertThat(a.getRequirementClassConcepts())
                    .as("check requirementClassConcepts")
                    .isEqualTo(expected.getRequirementClassConcepts())
            );
    }
}
