package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassAttributeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassAttributeAllPropertiesEquals(ClassAttribute expected, ClassAttribute actual) {
        assertClassAttributeAutoGeneratedPropertiesEquals(expected, actual);
        assertClassAttributeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassAttributeAllUpdatablePropertiesEquals(ClassAttribute expected, ClassAttribute actual) {
        assertClassAttributeUpdatableFieldsEquals(expected, actual);
        assertClassAttributeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassAttributeAutoGeneratedPropertiesEquals(ClassAttribute expected, ClassAttribute actual) {
        assertThat(actual)
            .as("Verify ClassAttribute auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassAttributeUpdatableFieldsEquals(ClassAttribute expected, ClassAttribute actual) {
        assertThat(actual)
            .as("Verify ClassAttribute relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getVisibility()).as("check visibility").isEqualTo(expected.getVisibility()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassAttributeUpdatableRelationshipsEquals(ClassAttribute expected, ClassAttribute actual) {
        assertThat(actual)
            .as("Verify ClassAttribute relationships")
            .satisfies(a -> assertThat(a.getClassConcept()).as("check classConcept").isEqualTo(expected.getClassConcept()));
    }
}
