package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassOperationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassOperationAllPropertiesEquals(ClassOperation expected, ClassOperation actual) {
        assertClassOperationAutoGeneratedPropertiesEquals(expected, actual);
        assertClassOperationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassOperationAllUpdatablePropertiesEquals(ClassOperation expected, ClassOperation actual) {
        assertClassOperationUpdatableFieldsEquals(expected, actual);
        assertClassOperationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassOperationAutoGeneratedPropertiesEquals(ClassOperation expected, ClassOperation actual) {
        assertThat(actual)
            .as("Verify ClassOperation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassOperationUpdatableFieldsEquals(ClassOperation expected, ClassOperation actual) {
        assertThat(actual)
            .as("Verify ClassOperation relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getReturnType()).as("check returnType").isEqualTo(expected.getReturnType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassOperationUpdatableRelationshipsEquals(ClassOperation expected, ClassOperation actual) {
        assertThat(actual)
            .as("Verify ClassOperation relationships")
            .satisfies(a -> assertThat(a.getClassConcept()).as("check classConcept").isEqualTo(expected.getClassConcept()));
    }
}
