package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassRelationshipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRelationshipAllPropertiesEquals(ClassRelationship expected, ClassRelationship actual) {
        assertClassRelationshipAutoGeneratedPropertiesEquals(expected, actual);
        assertClassRelationshipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRelationshipAllUpdatablePropertiesEquals(ClassRelationship expected, ClassRelationship actual) {
        assertClassRelationshipUpdatableFieldsEquals(expected, actual);
        assertClassRelationshipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRelationshipAutoGeneratedPropertiesEquals(ClassRelationship expected, ClassRelationship actual) {
        assertThat(actual)
            .as("Verify ClassRelationship auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRelationshipUpdatableFieldsEquals(ClassRelationship expected, ClassRelationship actual) {
        assertThat(actual)
            .as("Verify ClassRelationship relevant properties")
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getTarget()).as("check target").isEqualTo(expected.getTarget()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a ->
                assertThat(a.getSourceMultiplicity()).as("check sourceMultiplicity").isEqualTo(expected.getSourceMultiplicity())
            )
            .satisfies(a ->
                assertThat(a.getTargetMultiplicity()).as("check targetMultiplicity").isEqualTo(expected.getTargetMultiplicity())
            )
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassRelationshipUpdatableRelationshipsEquals(ClassRelationship expected, ClassRelationship actual) {
        assertThat(actual)
            .as("Verify ClassRelationship relationships")
            .satisfies(a ->
                assertThat(a.getRequirementClassConcepts())
                    .as("check requirementClassConcepts")
                    .isEqualTo(expected.getRequirementClassConcepts())
            );
    }
}
