package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OperationParameterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperationParameterAllPropertiesEquals(OperationParameter expected, OperationParameter actual) {
        assertOperationParameterAutoGeneratedPropertiesEquals(expected, actual);
        assertOperationParameterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperationParameterAllUpdatablePropertiesEquals(OperationParameter expected, OperationParameter actual) {
        assertOperationParameterUpdatableFieldsEquals(expected, actual);
        assertOperationParameterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperationParameterAutoGeneratedPropertiesEquals(OperationParameter expected, OperationParameter actual) {
        assertThat(actual)
            .as("Verify OperationParameter auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperationParameterUpdatableFieldsEquals(OperationParameter expected, OperationParameter actual) {
        assertThat(actual)
            .as("Verify OperationParameter relevant properties")
            .satisfies(a -> assertThat(a.getParamName()).as("check paramName").isEqualTo(expected.getParamName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperationParameterUpdatableRelationshipsEquals(OperationParameter expected, OperationParameter actual) {
        assertThat(actual)
            .as("Verify OperationParameter relationships")
            .satisfies(a -> assertThat(a.getClassOperation()).as("check classOperation").isEqualTo(expected.getClassOperation()));
    }
}
