package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProjectStatisticsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectStatisticsAllPropertiesEquals(ProjectStatistics expected, ProjectStatistics actual) {
        assertProjectStatisticsAutoGeneratedPropertiesEquals(expected, actual);
        assertProjectStatisticsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectStatisticsAllUpdatablePropertiesEquals(ProjectStatistics expected, ProjectStatistics actual) {
        assertProjectStatisticsUpdatableFieldsEquals(expected, actual);
        assertProjectStatisticsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectStatisticsAutoGeneratedPropertiesEquals(ProjectStatistics expected, ProjectStatistics actual) {
        assertThat(actual)
            .as("Verify ProjectStatistics auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectStatisticsUpdatableFieldsEquals(ProjectStatistics expected, ProjectStatistics actual) {
        assertThat(actual)
            .as("Verify ProjectStatistics relevant properties")
            .satisfies(a -> assertThat(a.getRequirements()).as("check requirements").isEqualTo(expected.getRequirements()))
            .satisfies(a -> assertThat(a.getCompleted()).as("check completed").isEqualTo(expected.getCompleted()))
            .satisfies(a -> assertThat(a.getApproved()).as("check approved").isEqualTo(expected.getApproved()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectStatisticsUpdatableRelationshipsEquals(ProjectStatistics expected, ProjectStatistics actual) {
        // empty method
    }
}
