package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequirementClassConceptsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementClassConceptsAllPropertiesEquals(
        RequirementClassConcepts expected,
        RequirementClassConcepts actual
    ) {
        assertRequirementClassConceptsAutoGeneratedPropertiesEquals(expected, actual);
        assertRequirementClassConceptsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementClassConceptsAllUpdatablePropertiesEquals(
        RequirementClassConcepts expected,
        RequirementClassConcepts actual
    ) {
        assertRequirementClassConceptsUpdatableFieldsEquals(expected, actual);
        assertRequirementClassConceptsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementClassConceptsAutoGeneratedPropertiesEquals(
        RequirementClassConcepts expected,
        RequirementClassConcepts actual
    ) {
        assertThat(actual)
            .as("Verify RequirementClassConcepts auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementClassConceptsUpdatableFieldsEquals(
        RequirementClassConcepts expected,
        RequirementClassConcepts actual
    ) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementClassConceptsUpdatableRelationshipsEquals(
        RequirementClassConcepts expected,
        RequirementClassConcepts actual
    ) {
        // empty method
    }
}
