package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequirementUseCaseConceptsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementUseCaseConceptsAllPropertiesEquals(
        RequirementUseCaseConcepts expected,
        RequirementUseCaseConcepts actual
    ) {
        assertRequirementUseCaseConceptsAutoGeneratedPropertiesEquals(expected, actual);
        assertRequirementUseCaseConceptsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementUseCaseConceptsAllUpdatablePropertiesEquals(
        RequirementUseCaseConcepts expected,
        RequirementUseCaseConcepts actual
    ) {
        assertRequirementUseCaseConceptsUpdatableFieldsEquals(expected, actual);
        assertRequirementUseCaseConceptsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementUseCaseConceptsAutoGeneratedPropertiesEquals(
        RequirementUseCaseConcepts expected,
        RequirementUseCaseConcepts actual
    ) {
        assertThat(actual)
            .as("Verify RequirementUseCaseConcepts auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementUseCaseConceptsUpdatableFieldsEquals(
        RequirementUseCaseConcepts expected,
        RequirementUseCaseConcepts actual
    ) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementUseCaseConceptsUpdatableRelationshipsEquals(
        RequirementUseCaseConcepts expected,
        RequirementUseCaseConcepts actual
    ) {
        // empty method
    }
}
