package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequirementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementAllPropertiesEquals(Requirement expected, Requirement actual) {
        assertRequirementAutoGeneratedPropertiesEquals(expected, actual);
        assertRequirementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementAllUpdatablePropertiesEquals(Requirement expected, Requirement actual) {
        assertRequirementUpdatableFieldsEquals(expected, actual);
        assertRequirementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementAutoGeneratedPropertiesEquals(Requirement expected, Requirement actual) {
        assertThat(actual)
            .as("Verify Requirement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementUpdatableFieldsEquals(Requirement expected, Requirement actual) {
        assertThat(actual)
            .as("Verify Requirement relevant properties")
            .satisfies(a -> assertThat(a.getSentId()).as("check sentId").isEqualTo(expected.getSentId()))
            .satisfies(a -> assertThat(a.getText()).as("check text").isEqualTo(expected.getText()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getProjectId()).as("check projectId").isEqualTo(expected.getProjectId()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getSpecLevel()).as("check specLevel").isEqualTo(expected.getSpecLevel()))
            .satisfies(a -> assertThat(a.getClassDiagram()).as("check classDiagram").isEqualTo(expected.getClassDiagram()))
            .satisfies(a -> assertThat(a.getUseCaseDiagram()).as("check useCaseDiagram").isEqualTo(expected.getUseCaseDiagram()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementUpdatableRelationshipsEquals(Requirement expected, Requirement actual) {
        assertThat(actual)
            .as("Verify Requirement relationships")
            .satisfies(a -> assertThat(a.getUseCaseConcepts()).as("check useCaseConcepts").isEqualTo(expected.getUseCaseConcepts()))
            .satisfies(a -> assertThat(a.getClassConcepts()).as("check classConcepts").isEqualTo(expected.getClassConcepts()))
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
