package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UseCaseConditionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseConditionAllPropertiesEquals(UseCaseCondition expected, UseCaseCondition actual) {
        assertUseCaseConditionAutoGeneratedPropertiesEquals(expected, actual);
        assertUseCaseConditionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseConditionAllUpdatablePropertiesEquals(UseCaseCondition expected, UseCaseCondition actual) {
        assertUseCaseConditionUpdatableFieldsEquals(expected, actual);
        assertUseCaseConditionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseConditionAutoGeneratedPropertiesEquals(UseCaseCondition expected, UseCaseCondition actual) {
        assertThat(actual)
            .as("Verify UseCaseCondition auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseConditionUpdatableFieldsEquals(UseCaseCondition expected, UseCaseCondition actual) {
        assertThat(actual)
            .as("Verify UseCaseCondition relevant properties")
            .satisfies(a -> assertThat(a.getConditionText()).as("check conditionText").isEqualTo(expected.getConditionText()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseConditionUpdatableRelationshipsEquals(UseCaseCondition expected, UseCaseCondition actual) {
        assertThat(actual)
            .as("Verify UseCaseCondition relationships")
            .satisfies(a ->
                assertThat(a.getPreconditionUseCaseConcept())
                    .as("check preconditionUseCaseConcept")
                    .isEqualTo(expected.getPreconditionUseCaseConcept())
            )
            .satisfies(a ->
                assertThat(a.getPostconditionUseCaseConcept())
                    .as("check postconditionUseCaseConcept")
                    .isEqualTo(expected.getPostconditionUseCaseConcept())
            );
    }
}
