package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UseCaseActorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseActorAllPropertiesEquals(UseCaseActor expected, UseCaseActor actual) {
        assertUseCaseActorAutoGeneratedPropertiesEquals(expected, actual);
        assertUseCaseActorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseActorAllUpdatablePropertiesEquals(UseCaseActor expected, UseCaseActor actual) {
        assertUseCaseActorUpdatableFieldsEquals(expected, actual);
        assertUseCaseActorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseActorAutoGeneratedPropertiesEquals(UseCaseActor expected, UseCaseActor actual) {
        assertThat(actual)
            .as("Verify UseCaseActor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseActorUpdatableFieldsEquals(UseCaseActor expected, UseCaseActor actual) {
        assertThat(actual)
            .as("Verify UseCaseActor relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseActorUpdatableRelationshipsEquals(UseCaseActor expected, UseCaseActor actual) {
        assertThat(actual)
            .as("Verify UseCaseActor relationships")
            .satisfies(a ->
                assertThat(a.getRequirementUseCaseConcepts())
                    .as("check requirementUseCaseConcepts")
                    .isEqualTo(expected.getRequirementUseCaseConcepts())
            );
    }
}
