package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UseCaseRelationshipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseRelationshipAllPropertiesEquals(UseCaseRelationship expected, UseCaseRelationship actual) {
        assertUseCaseRelationshipAutoGeneratedPropertiesEquals(expected, actual);
        assertUseCaseRelationshipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseRelationshipAllUpdatablePropertiesEquals(UseCaseRelationship expected, UseCaseRelationship actual) {
        assertUseCaseRelationshipUpdatableFieldsEquals(expected, actual);
        assertUseCaseRelationshipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseRelationshipAutoGeneratedPropertiesEquals(UseCaseRelationship expected, UseCaseRelationship actual) {
        assertThat(actual)
            .as("Verify UseCaseRelationship auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseRelationshipUpdatableFieldsEquals(UseCaseRelationship expected, UseCaseRelationship actual) {
        assertThat(actual)
            .as("Verify UseCaseRelationship relevant properties")
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getTarget()).as("check target").isEqualTo(expected.getTarget()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseRelationshipUpdatableRelationshipsEquals(UseCaseRelationship expected, UseCaseRelationship actual) {
        assertThat(actual)
            .as("Verify UseCaseRelationship relationships")
            .satisfies(a ->
                assertThat(a.getRequirementUseCaseConcepts())
                    .as("check requirementUseCaseConcepts")
                    .isEqualTo(expected.getRequirementUseCaseConcepts())
            );
    }
}
