package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UseCaseActorRefAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseActorRefAllPropertiesEquals(UseCaseActorRef expected, UseCaseActorRef actual) {
        assertUseCaseActorRefAutoGeneratedPropertiesEquals(expected, actual);
        assertUseCaseActorRefAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseActorRefAllUpdatablePropertiesEquals(UseCaseActorRef expected, UseCaseActorRef actual) {
        assertUseCaseActorRefUpdatableFieldsEquals(expected, actual);
        assertUseCaseActorRefUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseActorRefAutoGeneratedPropertiesEquals(UseCaseActorRef expected, UseCaseActorRef actual) {
        assertThat(actual)
            .as("Verify UseCaseActorRef auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseActorRefUpdatableFieldsEquals(UseCaseActorRef expected, UseCaseActorRef actual) {
        assertThat(actual)
            .as("Verify UseCaseActorRef relevant properties")
            .satisfies(a -> assertThat(a.getActorName()).as("check actorName").isEqualTo(expected.getActorName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseActorRefUpdatableRelationshipsEquals(UseCaseActorRef expected, UseCaseActorRef actual) {
        assertThat(actual)
            .as("Verify UseCaseActorRef relationships")
            .satisfies(a ->
                assertThat(a.getPrimaryUseCaseConcept()).as("check primaryUseCaseConcept").isEqualTo(expected.getPrimaryUseCaseConcept())
            )
            .satisfies(a ->
                assertThat(a.getSecondaryUseCaseConcept())
                    .as("check secondaryUseCaseConcept")
                    .isEqualTo(expected.getSecondaryUseCaseConcept())
            );
    }
}
