package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UseCaseConceptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseConceptAllPropertiesEquals(UseCaseConcept expected, UseCaseConcept actual) {
        assertUseCaseConceptAutoGeneratedPropertiesEquals(expected, actual);
        assertUseCaseConceptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseConceptAllUpdatablePropertiesEquals(UseCaseConcept expected, UseCaseConcept actual) {
        assertUseCaseConceptUpdatableFieldsEquals(expected, actual);
        assertUseCaseConceptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseConceptAutoGeneratedPropertiesEquals(UseCaseConcept expected, UseCaseConcept actual) {
        assertThat(actual)
            .as("Verify UseCaseConcept auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseConceptUpdatableFieldsEquals(UseCaseConcept expected, UseCaseConcept actual) {
        assertThat(actual)
            .as("Verify UseCaseConcept relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTrigger()).as("check trigger").isEqualTo(expected.getTrigger()))
            .satisfies(a -> assertThat(a.getSystemBoundary()).as("check systemBoundary").isEqualTo(expected.getSystemBoundary()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseConceptUpdatableRelationshipsEquals(UseCaseConcept expected, UseCaseConcept actual) {
        assertThat(actual)
            .as("Verify UseCaseConcept relationships")
            .satisfies(a ->
                assertThat(a.getRequirementUseCaseConcepts())
                    .as("check requirementUseCaseConcepts")
                    .isEqualTo(expected.getRequirementUseCaseConcepts())
            );
    }
}
