package com.github.danimaniarqsoft.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UseCaseBusinessRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseBusinessRuleAllPropertiesEquals(UseCaseBusinessRule expected, UseCaseBusinessRule actual) {
        assertUseCaseBusinessRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertUseCaseBusinessRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseBusinessRuleAllUpdatablePropertiesEquals(UseCaseBusinessRule expected, UseCaseBusinessRule actual) {
        assertUseCaseBusinessRuleUpdatableFieldsEquals(expected, actual);
        assertUseCaseBusinessRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseBusinessRuleAutoGeneratedPropertiesEquals(UseCaseBusinessRule expected, UseCaseBusinessRule actual) {
        assertThat(actual)
            .as("Verify UseCaseBusinessRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseBusinessRuleUpdatableFieldsEquals(UseCaseBusinessRule expected, UseCaseBusinessRule actual) {
        assertThat(actual)
            .as("Verify UseCaseBusinessRule relevant properties")
            .satisfies(a -> assertThat(a.getRuleText()).as("check ruleText").isEqualTo(expected.getRuleText()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUseCaseBusinessRuleUpdatableRelationshipsEquals(UseCaseBusinessRule expected, UseCaseBusinessRule actual) {
        assertThat(actual)
            .as("Verify UseCaseBusinessRule relationships")
            .satisfies(a -> assertThat(a.getUseCaseConcept()).as("check useCaseConcept").isEqualTo(expected.getUseCaseConcept()));
    }
}
